// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdfecuztqhmnczbecjlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkZmVjdXp0cWhtbmN6YmVjamx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDg5NDEsImV4cCI6MjA2MDU4NDk0MX0.3j7WkAXt3bu9kNiLVq6xgG3cOIurJrzXXLHqjC50uYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);